name: hum_1618
description: A new Flutter project.


version: 1.0.0+1

environment:

  # Dart SDK Version
  # Note - If Dart version not correct,
  # refrerence ->  https://dartcode.org/docs/quickly-switching-between-sdk-versions/
  
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 0.3.1+1
  firebase_auth: ^0.8.3
  cloud_firestore:
  google_sign_in: ^4.0.1+1
  camera: any
  path_provider:
  


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # Picutres Assests 
  assets:
  
  - assets/
  